name: CI Securite

on: push

jobs:
  dependances:
    name: Dependances
    runs-on: ubuntu-latest
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Scan requirements.txt avec Trivy
        run: |
          docker run --rm \
            -v "$PWD/breakableflask":/project \
            aquasec/trivy:latest fs \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            /project/requirements.txt

  dockerfile:
    name: Dockerfile
    runs-on: ubuntu-latest
    needs: dependances
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Scan Dockerfile avec Trivy
        run: |
          docker run --rm \
            -v "$PWD/breakableflask":/project \
            aquasec/trivy:latest config \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            /project